FROM python:3.8

RUN mkdir -p /app
RUN mkdir -p /app/tmp
WORKDIR /app 

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

#setup folder
COPY ./deploy        ./deploy
COPY ./deploy/app.py .

# initialize environment
RUN pip install awslambdaric
COPY ./requirements.txt ./requirements.txt 
RUN pip install -r ./requirements.txt --no-cache

ENTRYPOINT [ "python", "-m", "awslambdaric" ]
CMD ["app.handler"]
